---
# To finalize installation
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/keystone-install.html

# Restart the Apache HTTP server
- meta: flush_handlers

- name: remove the SQLite database file
  file: 
    path: /var/lib/keystone/keystone.db
    state: absent
