---
# Create projects, users, and roles
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/keystone-users.html

# Create an administrative project, user, and role for administrative operations
# in your environment
- name: Create the admin project
  keystone_user:
    tenant: admin
    tenant_description: Admin Project
    token: "{{ os_identity_admin_token }}"

- name: Create the admin user
  shell:
    openstack user list | grep -q admin ||
    openstack user create --password "{{ os_project_admin_password }}" admin
  environment:
    OS_TOKEN: "{{ os_identity_admin_token }}"
    OS_URL: http://{{ os_identity_host }}:35357/v2.0
  register: st
  changed_when: "'admin' in st.stdout"

- name: Create the admin role and Add the admin role to the admin project and user
  keystone_user:
    user: admin
    role: admin
    tenant: admin
    token: "{{ os_identity_admin_token }}"

# This guide uses a service project that contains a unique user for each service
# that you add to your environment
- name: Create the service project
  keystone_user:
    tenant: service
    tenant_description: Service Project
    token: "{{ os_identity_admin_token }}"

# Regular (non-admin) tasks should use an unprivileged project and user. As an
# example, this guide creates the demo project and user
- name: Create the demo project
  keystone_user:
    tenant: demo
    tenant_description: Demo Project
    token: "{{ os_identity_admin_token }}"

- name: Create the demo user
  shell:
    openstack user list | grep -q demo ||
    openstack user create --password "{{ os_project_demo_password }}" demo
  environment:
    OS_TOKEN: "{{ os_identity_admin_token }}"
    OS_URL: http://{{ os_identity_host }}:35357/v2.0
  register: st
  changed_when: "'demo' in st.stdout"

- name: Create the user role and Add the user role to the demo project and user
  keystone_user:
    user: demo
    role: user
    tenant: demo
    token: "{{ os_identity_admin_token }}"
