---
# Create tenants, users, and roles
# See http://docs.openstack.org/juno/install-guide/install/apt/content/keystone-users.html

# Create an administrative tenant, user, and role for administrative operations in your environment
# See tenants.yml, users.yml and roles.yml in the demo role

# Create an administrative tenant, user, and role for administrative operations in your environment
# See tenants.yml, users.yml and roles.yml in the demo role

# OpenStack services also require a tenant, user, and role to interact with other services.
- name: Create the admin role
  keystone_user:
    tenant: service
    tenant_description: Service Tenant
    token: "{{ os_identity_admin_token }}"
