---
# Upload the image to the Image service using the QCOW2 disk format, bare
# container format, and public visibility so all projects can access it
#
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/glance-verify.html

- name: In each client environment script, configure the Image service client to use API version 2.0
  lineinfile:
    dest: "{{ item }}"
    line: export OS_IMAGE_API_VERSION=2
  with_items:
  - "{{ os_openrc_admin_path }}"
  - "{{ os_openrc_demo_path }}"

- name: Create a temporary local directory
  file:
    path: /tmp/images
    state: directory

- name: Download the image to the temporary local directory
  get_url:
    url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
    dest: /tmp/images/cirros-0.3.4-x86_64-disk.img

- name: Upload the image to the Image Service
  glance:
    name: cirros-0.3.4-x86_64
    file: /tmp/images/cirros-0.3.4-x86_64-disk.img
    disk_format: qcow2
    is_public: yes
    username: admin
    password: "{{ os_project_admin_password }}"
    tenant_name: admin
    auth_url: http://{{ os_identity_host }}:5000/v2.0
