---
- name: Restart the Compute services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - nova-api
  - nova-scheduler
  - nova-conductor

- name: Restart the Networking service
  service:
    name: neutron-server
    state: restarted
