---
# Message queue
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/ch_basic_environment.html#basics-message-queue

# To install the message queue service
- name: To install the message queue service
  apt:
    name: rabbitmq-server
    update_cache: yes
    cache_valid_time: 3600

# To configure the message queue service
- name: Add the openstack user and Permit configuration, write, and read access for the openstack user
  rabbitmq_user:
    user: openstack
    password: "{{ os_messaging_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
    force: yes
