define HELP
Available commands:

make something			Run example playbook
make prepare			Prepare required files.
make role			Install roles
make help			Show help
endef
export HELP

all: help

something:
	ansible-playbook playbooks/something.yml

prepare:
	@[ -e Vagrantfile ] || cp Vagrantfile.example Vagrantfile
	@[ -e hosts ] || cp hosts.example hosts
	@[ -e Makefile ] || cp Makefile.example Makefile

role:
	@[ -n "$$(sed 's/^ *-*\|#.*//g' requirements.yml | grep -v ^$$)" ] && \
	  sudo bash -lc "ansible-galaxy install -i -r requirements.yml" || \
	  echo There is no role defined.

help:
	@echo "$$HELP"
