---
# Database
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/ch_basic_environment.html#basics-database
- name: Install the packages
  apt:
    name: "{{ item }}"
  with_items:
  - mariadb-server
  - python-mysqldb

- name: set the bind-address key
  ini_file:
    dest: /etc/mysql/my.cnf
    section: mysqld
    option: bind-address
    value: 0.0.0.0
  notify: Restart the database service

- name: In the [mysqld] section, set the following keys to enable useful options and the UTF-8 character set
  ini_file:
    dest: /etc/mysql/my.cnf
    section: mysqld
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: default-storage-engine
    value: innodb
  - option: innodb_file_per_table
    value: 1
  - option: collation-server
    value: utf8_general_ci
  - option: init-connect
    value: 'SET NAMES utf8'
  - option: character-set-server
    value: utf8
  notify: Restart the database service

- include: mysql_secure_installation.yml

# Restart the database service if needed
- meta: flush_handlers
