---
# To configure networking
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/ch_basic_environment.html#basics-neutron-networking-network-node

- name: Ensure the source line exists
  lineinfile:
    dest: /etc/network/interfaces
    line: source /etc/network/interfaces.d/*.cfg

- name: Configure the second interface as the instance tunnels interface if needed
  template:
    src: tunnels_interface.cfg
    dest: /etc/network/interfaces.d/{{ os_networking_tunnels_interface }}.cfg
  notify:
  - Reboot the system to activate the changes
  - Wait until rebooting
  when: os_networking_tunnels_interface != ""

- name: Configure the third interface as the external interface
  template:
    src: external_interface.cfg
    dest: /etc/network/interfaces.d/{{ os_networking_external_interface }}.cfg
  notify:
  - Reboot the system to activate the changes
  - Wait until rebooting

# Install and configure network node
# See http://docs.openstack.org/juno/install-guide/install/apt/content/neutron-network-node.html

# To configure prerequisites

- name: Edit the /etc/sysctl.conf file to contain the following parameters
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
  - regexp: ^#net\.ipv4\.ip_forward=
    line: net.ipv4.ip_forward=1
  - regexp: ^#net\.ipv4\.conf\.all\.rp_filter=
    line: net.ipv4.conf.all.rp_filter=0
  - regexp: ^#net\.ipv4\.conf\.default\.rp_filter=
    line: net.ipv4.conf.default.rp_filter=0
  notify: Implement the changes
