---
# Upload the image to the Image Service
# See http://docs.openstack.org/juno/install-guide/install/apt/content/glance-verify.html

- name: Create and change into a temporary local directory
  file:
    path: /tmp/images
    state: directory

- name: Download the image to the temporary local directory
  get_url:
    url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
    dest: /tmp/images/cirros-0.3.4-x86_64-disk.img

- name: Upload the image to the Image Service
  glance:
    name: cirros-0.3.4-x86_64
    file: /tmp/images/cirros-0.3.4-x86_64-disk.img
    disk_format: qcow2
    is_public: yes
    username: admin
    password: "{{ os_tenant_admin_password }}"
    tenant_name: admin
    auth_url: http://{{ os_identity_host }}:5000/v2.0
