---
# To create a router on the tenant network and attach the external and tenant networks to it
# See http://docs.openstack.org/juno/install-guide/install/apt/content/neutron_initial-tenant-network.html

- name: Create the router
  neutron_router:
    name: demo-router
    login_username: demo
    login_password: "{{ os_tenant_demo_password }}"
    login_tenant_name: demo
    auth_url: http://{{ os_identity_host }}:5000/v2.0

- name: Attach the router to the external network by setting it as the gateway
  neutron_router_gateway:
    router_name: demo-router
    network_name: ext-net
    login_username: admin
    login_password: "{{ os_tenant_admin_password }}"
    login_tenant_name: admin
    auth_url: http://{{ os_identity_host }}:5000/v2.0

- name: Attach the router to the demo tenant subnet
  neutron_router_interface:
    router_name: demo-router
    subnet_name: demo-subnet
    login_username: demo
    login_password: "{{ os_tenant_demo_password }}"
    login_tenant_name: demo
    auth_url: http://{{ os_identity_host }}:5000/v2.0
