---
# Tenant network
# See http://docs.openstack.org/juno/install-guide/install/apt/content/neutron_initial-tenant-network.html

# To create the tenant network

- name: Create the network
  neutron_network:
    name: demo-net
    login_username: demo
    login_password: "{{ os_tenant_demo_password }}"
    login_tenant_name: demo
    auth_url: http://{{ os_identity_host }}:5000/v2.0

- name: Create the subnet
  neutron_subnet:
    name: demo-subnet
    network_name: demo-net
    gateway_ip: 192.168.1.1
    dns_nameservers: "{{ os_tenant_subnet_nameservers }}"
    cidr: 192.168.1.0/24
    login_username: demo
    login_password: "{{ os_tenant_demo_password }}"
    login_tenant_name: demo
    auth_url: http://{{ os_identity_host }}:5000/v2.0

- pause:
    seconds: 30
