---
# Create tenants, users, and roles
# See http://docs.openstack.org/juno/install-guide/install/apt/content/keystone-users.html

# Create an administrative tenant, user, and role for administrative operations in your environment
- name: Create the admin tenant
  keystone_user:
    tenant: admin
    tenant_description: Admin Tenant
    token: "{{ os_identity_admin_token }}"

# Create an administrative tenant, user, and role for administrative operations in your environment
- name: Create the demo tenant
  keystone_user:
    tenant: demo
    tenant_description: Demo Tenant
    token: "{{ os_identity_admin_token }}"
