---
# See http://drbl.org/installation/02-install-required-packages.php
# Setup DRBL server - II. Install the required packages on server

- name: Install the DRBL key
  apt_key:
    url: http://drbl.org/GPG-KEY-DRBL

- name: Edit /etc/apt/sources.list
  apt_repository:
    repo: "deb http://free.nchc.org.tw/drbl-core drbl stable"

- name: Execute "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Execute "apt-get install drbl" to install drbl program
  apt:
    name: drbl
  notify:
    - Reboot
    - Wait until rebooting

# See http://drbl.org/installation/03-setup-client.php
# Setup DRBL server - III. Set up the file system for the client in the Server

- name: Run drblsrv -i
  command: drblsrv
    --install
    --netinstall n
    --console-output n
    --upgrade_system n
    --client_kernel_from 1

- name: Run drblpush -i
  script: drblpush.exp

- name: Run drbl-netinstall -i
  command: drbl-netinstall
    --install ubuntu
    --skip-rerun-gen
    --overwrite
