---
# To install the Networking components
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-compute-node.html

- name: install the Networking components
  apt:
    name: "{{ item }}"
  with_items:
  - neutron-plugin-ml2
  - neutron-plugin-openvswitch-agent

# To configure the Networking common components
# Edit the /etc/neutron/neutron.conf file and complete the following actions

- name: In the [DEFAULT] and [oslo_messaging_rabbit] sections, configure RabbitMQ message queue access
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - section: DEFAULT
    option: rpc_backend
    value: rabbit
  - section: oslo_messaging_rabbit
    option: rabbit_host
    value: "{{ os_messaging_host }}"
  - section: oslo_messaging_rabbit
    option: rabbit_userid
    value: openstack
  - section: oslo_messaging_rabbit
    option: rabbit_password
    value: "{{ os_messaging_password }}"
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

- name: In the [DEFAULT] and [keystone_authtoken] sections, configure Identity service access
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - section: DEFAULT
    option: auth_strategy
    value: keystone
  - section: keystone_authtoken
    option: auth_uri
    value: http://{{ os_identity_host }}:5000
  - section: keystone_authtoken
    option: auth_url
    value: http://{{ os_identity_host }}:35357
  - section: keystone_authtoken
    option: auth_plugin
    value: password
  - section: keystone_authtoken
    option: project_domain_id
    value: default
  - section: keystone_authtoken
    option: user_domain_id
    value: default
  - section: keystone_authtoken
    option: project_name
    value: service
  - section: keystone_authtoken
    option: username
    value: neutron
  - section: keystone_authtoken
    option: password
    value: "{{ os_networking_admin_password }}"
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

- name: In the [DEFAULT] section, enable the Modular Layer 2 (ML2) plug-in, router service, and overlapping IP addresses
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: DEFAULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: core_plugin
    value: ml2
  - option: service_plugins
    value: router
  - option: allow_overlapping_ips
    value: True
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

- name: (Optional) To assist with troubleshooting, enable verbose logging in the [DEFAULT] section
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: DEFAULT
    option: verbose
    value: True
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

# To configure the Modular Layer 2 (ML2) plug-in
# Edit the /etc/neutron/plugins/ml2/ml2_conf.ini file and complete the following actions

- name: In the [ml2] section, enable the flat, VLAN, generic routing encapsulation (GRE), and virtual extensible LAN (VXLAN) network type drivers, GRE tenant networks, and the OVS mechanism driver
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: ml2
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: type_drivers
    value: flat,vlan,gre,vxlan
  - option: tenant_network_types
    value: gre
  - option: mechanism_drivers
    value: openvswitch
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

- name: In the [ml2_type_gre] section, configure the tunnel identifier (id) range
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: ml2_type_gre
    option: tunnel_id_ranges
    value: 1:1000
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

- name: In the [securitygroup] section, enable security groups, enable ipset, and configure the OVS iptables firewall driver
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: securitygroup
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: enable_security_group
    value: True
  - option: enable_ipset
    value: True
  - option: firewall_driver
    value: neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

- name: In the [ovs] section, enable tunnels and configure the local tunnel endpoint
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: ovs
    option: local_ip
    value: "{{ os_networking_tunnels_address }}"
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

- name: In the [agent] section, enable GRE tunnels
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: agent
    option: tunnel_types
    value: gre
  notify:
  - Restart the OVS service
  - Restart the Open vSwitch (OVS) agent

# To configure the Open vSwitch (OVS) service

# To configure Compute to use Networking
# See networking.yml in the compute-node role
