---
# To configure the Networking server component
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-controller-node.html

# To install the Networking components

- name: install the Networking components
  apt:
    name: "{{ item }}"
  with_items:
  - neutron-server
  - neutron-plugin-ml2
  - python-neutronclient

# To configure the Networking server component
# Edit the /etc/neutron/neutron.conf file and complete the following actions

- name: In the [database] section, configure database access
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: database
    option: connection
    value: mysql://neutron:{{ os_networking_database_password }}@controller/neutron
  notify: Restart the Networking service

- name: In the [DEFAULT] and [oslo_messaging_rabbit] sections, configure RabbitMQ message queue access
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: "{{ item.section}}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - section: DEFAULT
    option: rpc_backend
    value: rabbit
  - section: oslo_messaging_rabbit
    option: rabbit_host
    value: controller
  - section: oslo_messaging_rabbit
    option: rabbit_userid
    value: openstack
  - section: oslo_messaging_rabbit
    option: rabbit_password
    value: "{{ os_messaging_password }}"
  notify: Restart the Networking service

- name: In the [DEFAULT] and [keystone_authtoken] sections, configure Identity service access
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - section: DEFAULT
    option: auth_strategy
    value: keystone
  - section: keystone_authtoken
    option: auth_uri
    value: http://{{ os_identity_host }}:5000
  - section: keystone_authtoken
    option: auth_url
    value: http://{{ os_identity_host }}:35357
  - section: keystone_authtoken
    option: auth_plugin
    value: password
  - section: keystone_authtoken
    option: project_domain_id
    value: default
  - section: keystone_authtoken
    option: user_domain_id
    value: default
  - section: keystone_authtoken
    option: project_name
    value: service
  - section: keystone_authtoken
    option: username
    value: neutron
  - section: keystone_authtoken
    option: password
    value: "{{ os_networking_admin_password }}"
  notify: Restart the Networking service

- name: In the [DEFAULT] section, enable the Modular Layer 2 (ML2) plug-in, router service, and overlapping IP addresses
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: DEFAULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: core_plugin
    value: ml2
  - option: service_plugins
    value: router
  - option: allow_overlapping_ips
    value: True
  notify: Restart the Networking service

- name: In the [DEFAULT] and [nova] sections, configure Networking to notify Compute of network topology changes
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - section: DEFAULT
    option: notify_nova_on_port_status_changes
    value: True
  - section: DEFAULT
    option: notify_nova_on_port_data_changes
    value: True
  - section: DEFAULT
    option: nova_url
    value: http://{{ os_identity_host }}:8774/v2
  - section: nova
    option: auth_url
    value: http://{{ os_identity_host }}:35357
  - section: nova
    option: auth_plugin
    value: password
  - section: nova
    option: project_domain_id
    value: default
  - section: nova
    option: user_domain_id
    value: default
  - section: nova
    option: region_name
    value: regionOne
  - section: nova
    option: project_name
    value: service
  - section: nova
    option: username
    value: nova
  - section: nova
    option: password
    value: "{{ os_compute_admin_password }}"
  notify: Restart the Networking service

- name: (Optional) To assist with troubleshooting, enable verbose logging in the [DEFAULT] section
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: DEFAULT
    option: verbose
    value: True
  notify: Restart the Networking service

# To configure the Modular Layer 2 (ML2) plug-in
# Edit the /etc/neutron/plugins/ml2/ml2_conf.ini file and complete the following actions

- name: In the [ml2] section, enable the flat, VLAN, generic routing encapsulation (GRE), and virtual extensible LAN (VXLAN) network type drivers, GRE tenant networks, and the OVS mechanism driver
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: ml2
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: type_drivers
    value: flat,vlan,gre,vxlan
  - option: tenant_network_types
    value: gre
  - option: mechanism_drivers
    value: openvswitch
  notify: Restart the Networking service

- name: In the [ml2_type_gre] section, configure the tunnel identifier (id) range
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: ml2_type_gre
    option: tunnel_id_ranges
    value: 1:1000
  notify: Restart the Networking service

- name: In the [securitygroup] section, enable security groups, enable ipset, and configure the OVS iptables firewall driver
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: securitygroup
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: enable_security_group
    value: True
  - option: enable_ipset
    value: True
  - option: firewall_driver
    value: neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
  notify: Restart the Networking service

# To configure Compute to use Networking
# Edit the /etc/nova/nova.conf file on the controller node and complete the following actions

- name: In the [DEFAULT] section, configure the APIs and drivers
  ini_file:
    dest: /etc/nova/nova.conf
    section: DEFAULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: network_api_class
    value: nova.network.neutronv2.api.API
  - option: security_group_api
    value: neutron
  - option: linuxnet_interface_driver
    value: nova.network.linux_net.LinuxOVSInterfaceDriver
  - option: firewall_driver
    value: nova.virt.firewall.NoopFirewallDriver
  notify: Restart the Compute services

- name: In the [neutron] section, configure access options
  ini_file:
    dest: /etc/nova/nova.conf
    section: neutron
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: url
    value: http://{{ os_networking_controller_host }}:9696
  - option: auth_strategy
    value: keystone
  - option: admin_auth_url
    value: http://{{ os_identity_host }}:35357/v2.0
  - option: admin_tenant_name
    value: service
  - option: admin_username
    value: neutron
  - option: admin_password
    value: "{{ os_networking_admin_password }}"
  notify: Restart the Compute services
