---
- name: Implement the changes
  shell: sysctl -p

- name: Restart the OVS service
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - openvswitch-switch

- name: Restart the Open vSwitch (OVS) agent
  shell: service neutron-plugin-openvswitch-agent restart
