---
# Install and configure
# See http://docs.openstack.org/juno/install-guide/install/apt/content/keystone-install.html
- hosts: controller
  roles:
  - role: identity
    os_database_root_password: "{{ database_password }}"
    os_identity_database_password: "{{ KEYSTONE_DBPASS }}"
    os_identity_host: controller
    os_identity_admin_token: "{{ ADMIN_TOKEN }}"
  sudo: yes
