---
# Install and configure
# See http://docs.openstack.org/juno/install-guide/install/apt/content/ch_glance.html
- hosts: control-hosts
  roles:
  - role: image
    os_database_root_password: "{{ database_password }}"
    os_image_database_password: "{{ GLANCE_DBPASS }}"
    os_image_admin_password: "{{ GLANCE_PASS }}"
    os_identity_host: controller
    os_image_host: controller
    os_database_host: controller
    os_project_admin_password: "{{ ADMIN_PASS }}"
    os_openrc_admin_path: /root/admin-openrc.sh
    os_openrc_demo_path: /root/demo-openrc.sh
  sudo: yes
