---
# Messaging server
# See http://docs.openstack.org/juno/install-guide/install/apt/content/ch_basic_environment.html#basics-messaging-server
- hosts: control-hosts
  roles:
  - role: messaging
    os_messaging_password: "{{ RABBIT_PASS }}"
  sudo: yes
