---
# Install and configure network node
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-network-node.html
- hosts: network
  roles:
  - role: networking-network-node
    os_networking_admin_password: "{{ NEUTRON_PASS }}"
    os_messaging_password: "{{ RABBIT_PASS }}"
    os_messaging_host: controller
    os_identity_host: controller
    os_compute_controller_host: controller
    os_networking_metadata_secret: "{{ METADATA_SECRET }}"
    os_networking_external_interface: "{{ INTERFACE_NAME }}"
    os_networking_tunnels_interface: "{{ tunnels_interface }}"
    os_networking_tunnels_address: "{{ INSTANCE_TUNNELS_INTERFACE_IP_ADDRESS }}"
    os_networking_tunnels_netmask: "{{ tunnels_interface_netmask }}"
  sudo: yes
