---
# Install and configure compute node
# See http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-compute-node.html
- hosts: computes
  roles:
  - role: networking-compute-node
    os_networking_admin_password: "{{ NEUTRON_PASS }}"
    os_messaging_password: "{{ RABBIT_PASS }}"
    os_messaging_host: controller
    os_identity_host: controller
    os_networking_tunnels_address: "{{ INSTANCE_TUNNELS_INTERFACE_IP_ADDRESS }}"
  sudo: yes
