---
- name: Ensure specific ruby is installed
  sudo: yes
  command: su - {{ rbenv.user }} -c "bash -lc 'rbenv install -s {{ ruby.version }}'"

- name: Ensure specific ruby is enabled
  sudo: yes
  command: su - {{ rbenv.user }} -c "bash -lc 'rbenv global {{ ruby.version }}'"

- name: Ensure gem itself is updated
  sudo: yes
  command: su - {{ rbenv.user }} -c "bash -lc 'gem update --system'"

- name: Ensure that the packages for general use are installed
  sudo: yes
  command: su - {{ rbenv.user }} -c "bash -lc 'gem install {{ item }} --no-ri --no-rdoc'"
  with_items:
    - bundler
    - pry
    - pry-doc
